[settings]

# Full list of voices: https://huggingface.co/hexgrad/Kokoro-82M/blob/main/VOICES.md
VOICE = bm_lewis
BRITISH = true
NEWLINE_PAUSE = 0.5
SENTENCE_PAUSE = 0.7

ARTIST = Grace Keller
BOOK_TITLE = Guardian of Light

# Shows text chunks and pause times.
DEBUG = false
